name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name "andrijajovanovic98"
          git config user.email "andrija.jovanovic1998@gmail.com"
          git add -A
          git commit -m "generated"
          git push https://andrijajovanovic98:${{ secrets.GITHUB_TOKEN }}@github.com/andrijajovanovic98/andrijajovanovic98.git
